### PR TITLE
Re-apply fix for 401 error on iOS11

### PR DESCRIPTION
**Pull request by JohnKis**
It appears that #3 has reverted my changes that fixed the authorisation error on iOS11, therefore I'm submitting this PR again.

### CODE REVIEW

**Comment by alcheck** [comment]
Hi John,

Finally I’ve updated my 6s up to iOS11 and tested the app in real environment (I’ve checked the app on my Zyxel Giga WF router and transmission-bt server on my Mac). I had no issues at all. All works fine so 
I suggest you to clone the whole project again (previous branch was totally wrong, I’ve upload very old version to gitHub). The current version on master branch is up to date! Thanks!

**Comment by JohnKis** [comment]
Hi there,

I’ll try again tomorrow, however I’m certain that it didn’t work for me, even on the latest master.

The difference might be that I’m accessing my server over the Internet using https. I’ll try again tomorrow locally and see if it makes a difference.

Best,
John

**Comment by alcheck** [comment]
Hi,

Oh, I didn’t tested on https yet - that could be the point. I should test it too, though I don’t know how to configure transmission-bt on https :)

**Comment by JohnKis** [comment]
Could well be the cause then. I’ll test it tomorrow on http locally.

I use nginx as a proxy and letsencrypt for generating a valid ssl certificate for free. Just mentioning it in case you’d like to set up yours similarly ;) It’s very handy that I can control my transmission client even when I’m on the go.

**Comment by alcheck** [comment]
Though https support was from start of the project I still had not chance to test it, basically because transmission has not build-in https-rpc support, so your help with that issue would be great.

**Comment by JohnKis** [comment]
I did a fresh build from master and installed it on my iPhone 6 and tried connecting locally with https and it still doesn't work.

I'm getting a 401 accompanied with the following log messages:
`2017-10-17 22:14:00.030516+0100 TransmissionRPCClient[2319:1518554] CredStore - performQuery - Error copying matching creds.  Error=-25300, query={
    atyp = http;
    class = inet;
    "m_Limit" = "m_LimitAll";
    ptcl = http;
    "r_Attributes" = 1;
    sdmn = Transmission;
    srvr = "192.168.1.21";
    sync = syna;
}`

My transmission client is transmission daemon on Ubuntu. The exact version is: 2.92-1ubuntu1~16.104.2 amd64

As for the setting up https, it's not too complicated. What OS are you using? As I mentioned, I'm running transmission on linux so I can share my exact config, or we can try to make it work on macOS or Windows.

**Comment by JohnKis** [comment]
This just popped in my mind: do you have 'Require authentication' enabled for remote access? I think on GUI clients it's disabled by default. If you don't, that would explain why you aren't getting 401 errors, since there's no auth challenge to respond to.

**Comment by alcheck** [comment]
Hi John,

All of my servers require authentication for remote control. I have mac so we could try to configure https access.

Отправлено с iPad

**Comment by JohnKis** [comment]
Hi Alexey,

Ok, I'll set up my Mac and test against that as well. I'll share the info about configuring https on Mac once I managed to do it.

**Comment by JohnKis** [comment]
I did a quick test against Transmission on Mac (over http) and I can confirm it worked without my fix.

So it seems transmission on Linux sends the authentication challenge in a different way than transmission on Mac.

I'll test on Mac using https once I managed to set it up, and I'll be back with my findings. I'm suspecting it's gonna work absolutely fine since Transmission Linux didn't work for me on http either without the fix.

EDIT:
To make it less confusing, please find this summary below:

iOS | Transmission | Protocol | Working
--- | --- | --- | ---
10.3 | Mac | Http | Yes
11.0 | Mac | Http | Yes
10.3 | Ubuntu | Http | Yes
10.3 | Ubuntu | Https | Yes
11.0 | Ubuntu | Http | No
11.0 | Ubuntu | Https | No

**Comment by alcheck** [comment]
Hi John,

Thanks a lot for your work on this issue, today I going to test the app with windows port of tr-bt. I'll report the status when I funish.

**Comment by JohnKis** [comment]
I figured out what's the problem. It has noting to do with the OS. On my client I used a quite long password and this appears to be making it fail on iOS 11 (works fine on 10). I found that if you use a 48 character long password, the authorisation will fail (without my changes). When I'll have a moment, I'll check the base64 string and compare it with iOS 10. Something could've changed between the two versions.

At least now we now what is causing the issue :)

**Comment by alcheck** [comment]
Hi John,

And I could add to that matter that I’ve tested the app on Windows Transmission-bt daemon service and it works fine. So we both tested the app on various platforms :) I’m very surprised that you use so loooooong passwords I even didn’t remember max password length checkings in the app.
>

**Comment by JohnKis** [comment]
Since my Transmission client is accessible on the WAN as well, I like to use long generated passwords :) I don’t think it’s gonna be an explicit length issue, since the same password is working fine on iOS 10. It only fails on iOS 11. I’ll compare the base64 authorization strings between the two version and see how they differ.

**Comment by JohnKis** [comment]
Closing pull request since a better fix has been introduced in #6.

(I'll let you know about configuring https on a separate channel)

**Pull request closed without merging**
